### ISSUE TITLE
Maestro no bool values on iOS

### ISSUE THREAD

**Issue by retyui** [iamolegga/react-native-launch-arguments#71]
Boolean values don't parsed  properly on iOS, see an example below 

maestro test:

```yaml
- launchApp:
    appId: "com.example.app"
    arguments:
      boolTrue: true
      boolFalse: false
      boolStrTrue: "true"
      boolStrFalse: "false"
```

JS part

```tsx
// Android
LaunchArguments.value() // {"boolFalse": false, "boolStrFalse": false, "boolStrTrue": true, "boolTrue": true}
NativeModules.LaunchArguments.value // {"boolFalse": false, "boolStrFalse": "false", "boolStrTrue": "true", "boolTrue": true}

// iOS
LaunchArguments.value() // {"boolStrFalse": false, "boolStrTrue": true}
NativeModules.LaunchArguments.value // {"boolStrFalse": "false", "boolStrTrue": "true"}
```

---

Docs:
- https://maestro.mobile.dev/api-reference/commands/launchapp#launch-arguments

**Comment by retyui** [comment]
I workaround I pass bool values as string and it solve my needs

```
- launchApp:
    appId: "com.example.app"
    arguments:
      isMaestro: "true"
```

```tsx
LaunchArguments.value().isMaestro // true
```
